<a href="https://colab.research.google.com/github/paigemb4/DS1002/blob/main/final%20homeworks/CR_%2B_PB_homework_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# More pandas exercises

Create a Colab notebook. Complete the tasks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

1.  Load the following dataset into Colab and perform the requested operations in code.

 Source: https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv

In [45]:
# Load pandas and the data
import pandas as pd
df = pd.read_csv('https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv')

In [46]:
# show how many rows and columns are in this dataset

source = "https://ds1002-resources.s3.amazonaws.com/data/ride_sharing.csv"
df = pd.read_csv(source)
num_rows = df.shape[0]
print("Number of rows: ", num_rows) #prints number of rows
num_columns = df.shape[1]
print("Number of columns: ", num_columns) #prints number of columns

Number of rows:  25760
Number of columns:  10

In [47]:
# The first column, "duration" is seen as a string.
# Using two snippets of code, clean this column up so that
# is now an integer (int64)

df['duration'] = df['duration'].replace('[^\d]+', '', regex=True) #replacing string
df['duration'] = df['duration'].astype('int64') #casts object to a specified dtype

In [48]:
df.info() #checking to make sure "duration" is now int64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25760 entries, 0 to 25759
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   duration         25760 non-null  int64
 1   station_A_id     25760 non-null  int64
 2   station_A_name   25760 non-null  object
 3   station_B_id     25760 non-null  int64
 4   station_B_name   25760 non-null  object
 5   bike_id          25760 non-null  int64
 6   user_type        25760 non-null  int64
 7   user_birth_year  25760 non-null  int64
 8   user_gender      25760 non-null  object
 9   tire_size        25760 non-null  int64
dtypes: int64(7), object(3)
memory usage: 2.0+ MB

In [49]:
# Now display the datatypes in the updated dataframe
print(df['duration'].dtypes)

int64

In [50]:
# Show the min and max values of ride durations (the shortest and longest rides)
# Hint: If 'df' is the name of your dataframe, simply specify the column name
# and then append the .min() or .max() methods.

min_duration = df['duration'].min() #establishing minimum
max_duration = df['duration'].max() #establising maximum

print("Shortest ride duration:", min_duration) #displaying minimum
print("Longest ride duration:", max_duration) #displaying maximum

Shortest ride duration: 1
Longest ride duration: 1372

In [51]:
# Create a new dataframe object and populate it with rides that are 60 minutes or less.
# Hint: Use the .query() method for the dataframe that we used in class.
short_rides = df.query('duration <= 60')

In [52]:
short_rides.head() #just getting a look at the new dataframe

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
1,24,3,Powell St BART Station (Market St at 4th St),118,Eureka Valley Recreation Center,5193,2,1965,Male,27
2,8,67,San Francisco Caltrain Station 2 (Townsend St...,23,The Embarcadero at Steuart St,3652,3,1993,Male,29
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
4,11,22,Howard St at Beale St,350,8th St at Brannan St,4626,2,1994,Male,27

In [53]:
# Now show both the min and max values of the duration column for your new dataset.
min_duration_short_rides = short_rides['duration'].min()
max_duration_short_rides = short_rides['duration'].max()

print("Shortest ride duration (60 minutes or less):", min_duration_short_rides)
print("Longest ride duration (60 minutes or less):", max_duration_short_rides)

Shortest ride duration (60 minutes or less): 1
Longest ride duration (60 minutes or less): 60

In [54]:
# Using the new dataframe, update it so that is ONLY has records where
# the tire_size is 26.
short_rides = short_rides.query('tire_size == 26') #changing the value of tire_size

In [55]:
short_rides #just taking a look to make sure the above code worked properly

,duration,station_A_id,station_A_name,station_B_id,station_B_name,bike_id,user_type,user_birth_year,user_gender,tire_size
0,12,81,Berry St at 4th St,323,Broadway at Kearny,5480,2,1959,Male,26
3,4,16,Steuart St at Market St,28,The Embarcadero at Bryant St,1883,1,1979,Male,26
6,16,67,San Francisco Caltrain Station 2 (Townsend St...,107,17th St at Dolores St,1035,2,1981,Male,26
9,5,30,San Francisco Caltrain (Townsend St at 4th St),62,Victoria Manalo Draves Park,333,1,1994,Male,26
12,7,3,Powell St BART Station (Market St at 4th St),27,Beale St at Harrison St,1863,3,1998,Male,26
...,...,...,...,...,...,...,...,...,...,...
25750,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,4372,2,1994,Male,26
25751,15,16,Steuart St at Market St,371,Lombard St at Columbus Ave,5246,1,1995,Male,26
25755,11,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5063,1,2000,Male,26
25756,10,15,San Francisco Ferry Building (Harry Bridges Pl...,34,Father Alfred E Boeddeker Park,5411,2,1998,Male,26
25757,14,15,San Francisco Ferry Building (Harry Bridges Pl...,42,San Francisco City Hall (Polk St at Grove St),5157,2,1995,Male,26

In [56]:
# Finally, produce a count of all records with FEMALE riders
# using the 26-inch wheeled rental bikes for their rentals of
# one hour or less.
female_riders_count = short_rides[short_rides['user_gender'] == 'Female'].shape[0]

print("Count of Female riders:", female_riders_count) #prints female riders

Count of Female riders: 2962

2. Find the file `more-messy-data.csv` on GitHub and upload it into Google Colab.

Create a new Pandas DataFrame from that data and perform the following steps.

In [57]:
#creating new dataframe from more-messy-data.csv

newdf = pd.read_csv('./more-messy-data.csv')

In [58]:
newdf #just want to see the new data frame

       id  sepal_length  sepal_width  petal_length petal_width     species
0       1           3.5          2.9           1.4         0.5   virginica
1       2           3.6          3.2           3.0         0.5      setosa
2       3           3.8          NaN           2.2         1.5      setosa
3       4           5.8          2.7           2.6         1.2   virginica
4       5           4.9          3.6           3.0         1.2   virginica
...   ...           ...          ...           ...         ...         ...
1311  412           NaN          3.6           2.9         0.5  Versicolor
1312  413           5.8          2.7           2.0         0.1  Versicolor
1313  414           3.3          3.7           1.3         2.8  Versicolor
1314  415           3.1          NaN           1.1         NaN  Versicolor
1315  416           4.3          2.5           1.3           1  Versicolor

[1316 rows x 6 columns]

In [59]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.

number_of_duplicates = newdf.duplicated().sum()

print("Number of duplicate rows:", number_of_duplicates) #prints value of duplicate rows

Number of duplicate rows: 287

In [60]:
# Next, remove all duplicate rows using Python.
data = newdf.drop_duplicates() #using .drop function to remove duplicate

In [70]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean.

sepal_length_mean = newdf['sepal_length'].mean()
sepal_width_mean = newdf['sepal_width'].mean()
petal_length_mean = newdf['petal_length'].mean()
petal_width_mean = newdf['petal_width'].mean()

# Fill NaN values with the respective column means
newdf['sepal_length'].fillna(sepal_length_mean, inplace=True)
newdf['sepal_width'].fillna(sepal_width_mean, inplace=True)
newdf['petal_length'].fillna(petal_length_mean, inplace=True)
newdf['petal_width'].fillna(petal_width_mean, inplace=True)

#if you run the two code blocks after this one and then rerun this code block the error will go away!

In [62]:
#had an error in the code block above so we are looking to see what could be wrong
#turns out 'petal_width' is an object not a float64
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1316 entries, 0 to 1315
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            1316 non-null   int64
 1   sepal_length  1244 non-null   float64
 2   sepal_width   1103 non-null   float64
 3   petal_length  1189 non-null   float64
 4   petal_width   1206 non-null   object
 5   species       1228 non-null   object
dtypes: float64(3), int64(1), object(2)
memory usage: 61.8+ KB

In [63]:
newdf['petal_width'] = pd.to_numeric(newdf['petal_width'], errors='coerce')
#turning 'petal_width' from an object to a float64
print(newdf.dtypes)

id                int64
sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [65]:
newdf #getting a look at updated dataframe

       id  sepal_length  sepal_width  petal_length  petal_width     species
0       1      3.500000     2.900000           1.4      0.50000   virginica
1       2      3.600000     3.200000           3.0      0.50000      setosa
2       3      3.800000     2.992747           2.2      1.50000      setosa
3       4      5.800000     2.700000           2.6      1.20000   virginica
4       5      4.900000     3.600000           3.0      1.20000   virginica
...   ...           ...          ...           ...          ...         ...
1311  412      4.529662     3.600000           2.9      0.50000  Versicolor
1312  413      5.800000     2.700000           2.0      0.10000  Versicolor
1313  414      3.300000     3.700000           1.3      2.80000  Versicolor
1314  415      3.100000     2.992747           1.1      1.55706  Versicolor
1315  416      4.300000     2.500000           1.3      1.00000  Versicolor

[1316 rows x 6 columns]

In [66]:
# Find any values in the dataframe that are still missing, and delete them.
# check for missing values
missing_values = df.isnull().sum()

# print columns with missing values
print("Columns with missing values:")
print(missing_values[missing_values > 0])

# remove rows with missing values
df = df.dropna() #using drop function

Columns with missing values:
Series([], dtype: int64)

In [67]:
# How many different species are there?

df['species'] = 'unknown'

num_species = df['species'].nunique() #finding how many species there are

print("The number of unique species in the dataset is equal to:")
print(num_species)

The number of unique species in the dataset is equal to:
1

In [68]:
# Clean up the 'species' variable so that there are exactly three different values.
unique_species = df['species'].unique()
unique_species == 3
'species'==3
print(unique_species)

['unknown']

3. Bonus:  Regular expressions

Ordinary (non-vanity) Virginia license plates have the form `ABC1234`, meaning they have three upper case letters followed by four digits.  Write a regular expression that matches any string of this form (and doesn't match anything else).  Test your expression with code to make sure it works.

To figure out out how to do this, start with the sample code below.  The `re` package has various functions related to regular expressions, including for example `match()`, which takes two arguments, first the regular expression and second the test string, and tests to see whether the *beginning* of the `test` string matches the pattern `exp`.

Note that `re.match(exp,test)` does not return a boolean variable, as you might expect (in other words, a match doesn't return `True` and a non-match `False`).  The type of object you get is called `re.Match`, which is a data type special to the `re` package.  (The reason for this is that the object contains more information than just whether there is a match or not.) However, you can turn it into a boolean using `bool()` if you want.

Include the following in the notebook you submit:

 1. A regular expression in a text chunk
 2. One or more code chunks in which you test several strings to verify that your regex is correct.
 3. Make sure you display the results of testing various strings.

 See this [documentation page](https://docs.python.org/3/howto/regex.html#regex-howto) for further help.

In [69]:
# Sample code for testing whether a string matches a regex

# First import this package for working with regular expressions
import re

# Here is an example.
# Play around with different expressions and test strings to see what happens.
exp = 'ab+'
test = 'aabbbc'

if re.match(exp,test):
  print("match!")
else:
  print("no match")

# uncomment this line if you want
print(type(re.match(exp,test)))

# uncomment this line if you want
print(bool(re.match(exp,test)))

no match
<class 'NoneType'>
False